name: CheckIT Security Scan → n8n

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download CheckIT binary
        run: |
          mkdir -p bin
          curl -L -o bin/bearer "https://bookish-happiness-94w9p45rrgq2pxgp-8000.app.github.dev/bearer"
          chmod +x bin/bearer
          # Nếu bạn muốn đổi tên thành checkit:
          mv bin/bearer bin/checkit

      - name: Run CheckIT scan
        id: scan
        continue-on-error: true
        run: |
          if [ -f "bin/checkit" ]; then
            ./bin/checkit scan . --format json --output results.json
          elif command -v checkit &> /dev/null; then
            checkit scan . --format json --output results.json
          else
            echo "CheckIT binary not found"
            exit 1
          fi
          
          if [ -f "results.json" ]; then
            echo "Scan completed"
            echo "scan_success=true" >> $GITHUB_OUTPUT
          else
            echo "No results.json generated"
            echo "scan_success=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Check results size
        id: check-size
        if: steps.scan.outputs.scan_success == 'true'
        run: |
          FILE_SIZE=$(stat -c%s "results.json" 2>/dev/null || stat -f%z "results.json")
          echo "results_size=$FILE_SIZE" >> $GITHUB_OUTPUT
          
          # If > 6MB, we'll upload as artifact
          if [ "$FILE_SIZE" -gt 6291456 ]; then
            echo "payload_mode=artifact" >> $GITHUB_OUTPUT
            echo "Results file is large ($FILE_SIZE bytes), will upload as artifact"
          else
            echo "payload_mode=direct" >> $GITHUB_OUTPUT
            echo "Results size OK ($FILE_SIZE bytes), will POST directly"
          fi
          
      - name: Enrich payload with metadata
        id: enrich
        if: steps.scan.outputs.scan_success == 'true'
        run: |
          # Create enriched payload
          cat > payload.json <<EOF
          {
            "metadata": {
              "repo": "${{ github.repository }}",
              "branch": "${{ github.ref_name }}",
              "commitSha": "${{ github.sha }}",
              "workflowUrl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "runId": "${{ github.run_id }}",
              "generatedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
              "triggeredBy": "${{ github.actor }}"
            },
            "findings": $(cat results.json | jq '.findings // []')
          }
          EOF
          
          echo "Payload enriched"
          
      - name: Upload artifact (fallback for large payloads)
        if: steps.check-size.outputs.payload_mode == 'artifact'
        uses: actions/upload-artifact@v4
        with:
          name: checkit-results-${{ github.run_id }}
          path: payload.json
          retention-days: 7
          
      - name: POST to n8n webhook
        id: post
        if: steps.scan.outputs.scan_success == 'true'
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
        run: |
          if [ -z "$N8N_WEBHOOK_URL" ]; then
            echo "N8N_WEBHOOK_URL secret not configured"
            exit 0
          fi
          
          # Retry logic with backoff
          MAX_RETRIES=3
          RETRY_DELAY=5
          
          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i/$MAX_RETRIES: POST to n8n webhook..."
            
            if [ "${{ steps.check-size.outputs.payload_mode }}" == "direct" ]; then
              # Direct POST
              HTTP_CODE=$(curl -s -o response.json -w "%{http_code}" \
                -X POST \
                -H "Content-Type: application/json" \
                -d @payload.json \
                "$N8N_WEBHOOK_URL")
            else
              # Artifact mode: POST manifest with artifact URL
              ARTIFACT_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
              HTTP_CODE=$(curl -s -o response.json -w "%{http_code}" \
                -X POST \
                -H "Content-Type: application/json" \
                -d "{\"mode\":\"artifact\",\"artifact_url\":\"$ARTIFACT_URL\",\"metadata\":$(cat payload.json | jq '.metadata')}" \
                "$N8N_WEBHOOK_URL")
            fi
            
            if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
              echo "POST successful (HTTP $HTTP_CODE)"
              cat response.json
              echo "post_success=true" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "POST failed (HTTP $HTTP_CODE)"
              cat response.json || echo "(no response body)"
              
              if [ $i -lt $MAX_RETRIES ]; then
                echo "Retrying in ${RETRY_DELAY}s..."
                sleep $RETRY_DELAY
                RETRY_DELAY=$((RETRY_DELAY * 2))
              fi
            fi
          done
          
          echo "POST failed after $MAX_RETRIES attempts"
          echo "post_success=false" >> $GITHUB_OUTPUT
          exit 1
          
      - name: Summary
        if: always()
        run: |
          echo "## CheckIT Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.scan.outputs.scan_success }}" == "true" ]; then
            TOTAL=$(cat results.json | jq '[.findings | to_entries[] | .value | length] | add // 0')
            echo "**Scan completed**" >> $GITHUB_STEP_SUMMARY
            echo "- Total findings: $TOTAL" >> $GITHUB_STEP_SUMMARY
            echo "- Results size: ${{ steps.check-size.outputs.results_size }} bytes" >> $GITHUB_STEP_SUMMARY
            echo "- Mode: ${{ steps.check-size.outputs.payload_mode }}" >> $GITHUB_STEP_SUMMARY
            
            if [ "${{ steps.post.outputs.post_success }}" == "true" ]; then
              echo "- Posted to n8n successfully" >> $GITHUB_STEP_SUMMARY
            else
              echo "- Failed to POST to n8n" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "**Scan failed or no results**" >> $GITHUB_STEP_SUMMARY
          fi
